--MUESTRA TODO LA TABLA"MOVIMIENTOS"
SELECT * FROM MOVIMIENTOS;
--MUESTRA UNICAMENTE LAS COLUMNAS "FECHA Y MONTO" DE LA TABLA "MOVIMIENTOS"
SELECT FECHA, MONTO FROM MOVIMIENTOS;

--ALIAS
SELECT MONTO AS CANTIDAD, MONTO FROM MOVIMIENTOS;

--CALCULOS SUMA(+), RESTA(-), MULTIPLICACION(*) Y DIVISION(/)
--EN EL SIGUIENTE COMANDO LA TABLA TOMA POR DEFAULT EL NOMBRE (MONTO*1.16)
SELECT MONTO, MONTO*1.16 FROM MOVIMIENTOS;
--EN ESTE COMANDO NOSOTROS LE DAMOS EL ALEAS (PRECIO_CON_IVA)
SELECT MONTO, MONTO*1.16 AS PRECIO_CON_IVA FROM MOVIMIENTOS;

--CONCATENACION DE TEXTOS
--EN ESTE RENGLON DE CODIGO HACEMOS UNA NUEVA COLUMNA LLAMADA"FECHA Y MONTO" DONDE UNIMOS LOS 
--VALORES DE LAS COLUMNAS (FECHA Y MONTO) DE LA TABLA MOVIMIENTOS
SELECT MONTO, FECHA, MONTO|| '-' || FECHA "FECHA Y MONTO" FROM MOVIMIENTOS;

--CONDICIONES
-- >MAYOR QUE
-- <MENOR QUE
-- >=MAYOR O IGUAL QUE
-- <=MENOR O IGUAL QUE 
-- =IGUAL
-- <>DISTINTO
-- !=DISTINTO
--EN EL SIGUIENTE RENGLON SE LE PIDE AL PROGRAMA QUE SOLO MUESTRE LOS DATOS DE LA COLUMNA MONTO QUE SEAN MAYORES A 6000
SELECT MONTO FROM MOVIMIENTOS WHERE MONTO>6000;

SELECT * FROM MOVIMIENTOS;

--VALORES LOGICOS
--MUESTRA UNICAMENTE LOS VALORES QUE SEAN IGUALES O MAYORES QUE 3000 Y MENORES O IGUALES A 11000
--EN LA TABLA MONTO USANDO "AND"
SELECT MONTO FROM MOVIMIENTOS WHERE MONTO>=3000 AND MONTO<=11000;
--MUESTRA UNICAMENTE LOS VALORES DE TIPO"RETIRO Y DEPOSITO" DE LA COLUMNA TIPO_OPERACION USANDO "OR"
SELECT TIPO_OPERACION FROM MOVIMIENTOS WHERE TIPO_OPERACION='RETIRO' OR TIPO_OPERACION='DEPOSITO';
SELECT TIPO_OPERACION FROM MOVIMIENTOS WHERE TIPO_OPERACION>'A' AND TIPO_OPERACION<'Z';

--BETWEEN
--MUESTRA LOS VALORES QUE SE ENCUENTRAN ENTRE 30000 Y 11000 DE LA COLUMNA MONTO USANDO "BETWEEN"
SELECT MONTO FROM MOVIMIENTOS WHERE MONTO BETWEEN 3000 AND 11000;

--IN
--MUESTRA UNICAMENTE LOS VALORES QUE SE INGRESAN(1500,3300,11000) DE LA COLUMNA MONTO
SELECT MONTO FROM MOVIMIENTOS WHERE MONTO IN (1500,3300,11000);

SELECT * FROM MOVIMIENTOS;

--LIKE
--MUESTRA UNICAMENTE LAS PALABRAS QUE COMIENCEN CON LA LETRA "D" DE LA COLUMNA TIPO_OPERACION
SELECT TIPO_OPERACION FROM MOVIMIENTOS WHERE TIPO_OPERACION LIKE 'D%';
--MUESTRA UNICAMENTE LAS PALABRAS QUE CUENTES COLOS CARACTERES INGRESADOS "R_TIROS"
SELECT TIPO_OPERACION FROM MOVIMIENTOS WHERE TIPO_OPERACION LIKE 'R_TIRO';

--IS NULL
--PEDIMOS QUE NOS MUESTRE LAS CASILLAS VACIAS DE LA COLUMNA MONTO
SELECT MONTO FROM MOVIMIENTOS WHERE MONTO IS NULL
--MUESTRA LAS CASILLAS QUE SI CONTIENEN UNA CANTIDAD EN LA COLUMNA MONTO
SELECT MONTO FROM MOVIMIENTOS WHERE MONTO IS NOT NULL

--PRECEDENCIA DE OPERADORES
--  1: *(MULTIPLICAR) /(DIVIDIR)
--  2: +(SUMA) -(RESTA)
--  3: ||(CONCATENACION)
--  4: COMPARACIONES(>,<,!=,...)
--  5: IS NULL, IS NOT NULL, LIKE, IN, NOT IN
--  6: NOT, NOT BETWEEN
--  7: NOT
--  8: AND
--  9: OR

--ORDENACION
--ORDENA LOS VALORES DE LA COLUMNA MONTO DE MENOR A MAYOR EN FORMA ASCENDENTE
SELECT MONTO FROM MOVIMIENTOS ORDER BY MONTO;
--ORDENA LOS VALORES DE LA COLUMNA MONTO DE MAYOR A MENOR EN FORMA DESCENDENTE AL ESCRIBIR "DESC"
SELECT MONTO FROM MOVIMIENTOS ORDER BY MONTO DESC;

--ORDENA LAS COLUMNAS QUE SE LE INGRESAN (FECHA, TIPO_OPERACION,MONTO)
SELECT FECHA, TIPO_OPERACION, MONTO FROM MOVIMIENTOS ORDER BY 1,2,3 ;

--MANEJO DE NULOS EN LAS ORACIONES
-- NULLS LAST
-- NULLS FIRST

-- EN ESTE CASO TODAS LAS CASILLAS DE LA COLUMNA FECHA ESTAN LLENAS CON ALGUN VALOR PERO SI HUBIERA ALGUNA VACIA
--DEBERIA APARECER AL INICIO YA QUE SE ESTA USANDO EL "NULLS FIRST"
SELECT FECHA, TIPO_OPERACION, MONTO FROM MOVIMIENTOS ORDER BY FECHA NULLS FIRST;

--VARIABLES DE SUSTITUCION
--CON ESTE CODIGO EL SISTEMA NOS MUESTRA EL LAS CASILLAS DONDE APAREZCA CUENTA_ID Y EL NUMERO QUE LE INGRESEMOS MANUALMENTE
SELECT CUENTA_ID FROM MOVIMIENTOS WHERE CUENTA_ID=&CUENTA;



