COMMIT;

--LINK REFERENCIA:    https://jorgesanchez.net/manuales/sql/select-basico-sql2016.html   DEL 5.1 - 5.5
--SELECCION DE TODOS LOS REGRISTROS DE UNA TABLA
SELECT * FROM ROL;

--SELECCION DE CAMPOS ESPECIFICOS DE ALGUNA TABLA
SELECT ROL_ID, SUELDO FROM ROL;

--SOLO SE CAMBIA EL NOMBRE TEMPORALMENTE CUANDO SE EJECUTA NO ES PERMANENTE
SELECT CLIENTE_ID AS "ID CLIENTE", NOMBRE AS "NOMBRE",CURP AS "CLAVE ÚNICA" FROM CLIENTES2;

--EL DISTINCT SE USA PARA EVITAR PALABRAS REPETIDAS
SELECT DISTINCT DESCRIPCION FROM TIPO_CUENTA;

--LOS OPERADORES + - * / SE PUEDEN USAR PARA HACER OPERACIONES SIN AFECTAR LA TABLA ORIGINAL, SOLO PARA OBTENER VALORES DE FORMA TEMPORAK
SELECT DESCRIPCION, SUELDO, SUELDO * 12 AS SUELDO_ANUAL FROM ROL;

--CONCATENACION
SELECT NOMBRE, APELLIDOS, NOMBRE || ' ' || APELLIDOS AS NOMBRE_COMPLETO FROM EMPLEADOS;
 
--OPERADORES COMPARACION
SELECT CLIENTE_ID, SALDO FROM CUENTAS WHERE SALDO > 20000;

--SELECT * FROM CUENTAS;

--VALORES LOGICOS AND / OR
SELECT CLIENTE_ID, SALDO FROM CUENTAS WHERE SALDO >= 10000 AND SALDO <= 50000;
--SELECT * FROM CUENTAS;

SELECT CLIENTE_ID, SALDO FROM CUENTAS WHERE SALDO > 90000 OR SALDO < 10000;

--BETWEEN
SELECT NUM_CUENTA, SALDO FROM CUENTAS WHERE SALDO BETWEEN 5000 AND 30000;

--IN
SELECT TIPO_ID, DESCRIPCION FROM TIPO_CUENTA WHERE TIPO_ID IN (1, 3);

--LIKE
SELECT * FROM CLIENTES2;
SELECT NOMBRE FROM CLIENTES2 WHERE NOMBRE LIKE 'A%';

SELECT FECHA_NAC FROM CLIENTES2 WHERE FECHA_NAC LIKE '0_/0_/9_';

--NULL
SELECT NOMBRE, DIRECCION FROM CLIENTES2 WHERE FECHA_NAC IS NULL;

--PROCEDENCIA DE OPERADORES SIN PARENTESIS
SELECT NUM_CUENTA, SALDO FROM CUENTAS WHERE TIPO_CUENTA_ID = 1 OR TIPO_CUENTA_ID = 2 AND SALDO >= 20000;

--CON PARENTESIS
SELECT NUM_CUENTA, SALDO FROM CUENTAS WHERE (TIPO_CUENTA_ID = 1 OR TIPO_CUENTA_ID = 2) AND SALDO >= 20000;

--ORDER BY
SELECT NOMBRE, CURP FROM CLIENTES2 ORDER BY NOMBRE;

--ASCENDENTE Y DESCENDENTE
SELECT * FROM CLIENTES2;
SELECT NOMBRE, FECHA_NAC FROM CLIENTES2 ORDER BY FECHA_NAC DESC;

--ORDENAR POR NUMERO DE COLUMNAS
SELECT NOMBRE, FECHA_NAC, DIRECCION FROM CLIENTES2 ORDER BY 2, 1;

--NULOS
SELECT NOMBRE, FECHA_NAC FROM CLIENTES2 ORDER BY FECHA_NAC NULLS FIRST;

-- Variable en condición numérica
SELECT CLIENTE_ID, NOMBRE, DIRECCION FROM CLIENTES2
WHERE CLIENTE_ID = &ID_CLIENTE;

-- Incorrecto (faltan comillas)
-- SELECT NOMBRE FROM CLIENTES2 WHERE NOMBRE = &NOM;

--VARIABLES DE SUSTITUCION
SELECT NOMBRE, DIRECCION FROM CLIENTES2
WHERE NOMBRE = '&NOM';

--REUTILIZAR LA MISMA VARIABLE
SELECT &&COLUMNA
FROM CLIENTES2
ORDER BY &COLUMNA;