-----------------------------------------EJERCICIOS-----------------------------------------
--sintaxis sencilla del comando SELECT
SELECT * FROM ROL;
SELECT * FROM CLIENTES2;
SELECT * FROM MOVIMIENTOS;
SELECT * FROM ABONOS;
SELECT * FROM CUENTAS;
SELECT * FROM TARJETAS;
SELECT * FROM TIPO_TARJETA;
SELECT * FROM TIPO_CUENTA;
SELECT * FROM PRESTAMOS;


SELECT DESCRIPCION,SUELDO FROM ROL;
SELECT CLIENTE_ID, NOMBRE, DIRECCION FROM CLIENTES2;
SELECT PRESTAMO,FECHA, MONTO FROM ABONOS;
SELECT NUM_CUENTA,TIPO_CUENTA_ID, SALDO FROM CUENTAS;
SELECT NUM_TARJETA,TIPO_TARJETA_ID FROM TARJETAS;
SELECT TIPO_ID, DESCRIPCION FROM TIPO_TARJETA;
SELECT DESCRIPCION, SALDO_MIN, SALDO_MAX FROM TIPO_CUENTA;
SELECT MONTO, INTERES FROM PRESTAMOS;


SELECT MONTO*(INTERES/100) FROM PRESTAMOS;

------------------------ALIAS
SELECT MONTO AS MONTO_ABONO, FECHA FROM ABONOS;
SELECT TIPO_ID, DESCRIPCION AS TIPO_TARJETA FROM TIPO_TARJETA;

SELECT MONTO AS "MONTO DEL ABONO", FECHA FROM ABONOS;
SELECT TIPO_ID AS "IDENTIFICADOR DE TARJETA", DESCRIPCION AS "TIPO DE TARJETA" FROM TIPO_TARJETA;

------------------------CALCULOS
SELECT MONTO, MONTO*(INTERES/100), MONTO + MONTO*(INTERES/100) FROM PRESTAMOS;
SELECT MONTO, MONTO*(INTERES/100) AS "INTERES TOTAL", MONTO + MONTO*(INTERES/100) AS "FINAL A PAGAR" FROM PRESTAMOS;

------------------------CONCATENACION DE TEXTOS
SELECT PRESTAMO_ID, FECHA, MONTO, PRESTAMO_ID||'_'||FECHA||'_'||PRESTAMO_ID "ID GENERADO" FROM ABONOS;

------------------------CONDICIONES
SELECT PRESTAMO_ID, FECHA, MONTO, PRESTAMO_ID||'_'||FECHA||'_'||PRESTAMO_ID "ID GENERADO" FROM ABONOS WHERE MONTO > 10000;

------------------------VALORES LOGICOS     NO SE INCLUYEN LOS LIMITES
SELECT PRESTAMO_ID, FECHA, MONTO FROM ABONOS WHERE MONTO < 10000 AND MONTO > 5000;
SELECT CLIENTE_ID, NUM_CUENTA, SALDO FROM CUENTAS WHERE SALDO < 15000 AND SALDO > 7999;

------------------------BETWEEN             SE INCLUYEN LOS LIMITES
SELECT PRESTAMO_ID, FECHA, MONTO FROM ABONOS WHERE MONTO BETWEEN 5000 AND 10000;
SELECT CLIENTE_ID, NUM_CUENTA, SALDO FROM CUENTAS WHERE SALDO BETWEEN 7999 AND 10000;

------------------------IN 
SELECT DESCRIPCION, SUELDO FROM ROL WHERE ROL_ID IN (1,2,3);
SELECT MONTO, INTERES FROM PRESTAMOS WHERE INTERES IN (5,7,9);

------------------------LIKE
SELECT PRESTAMO_ID, MONTO, FECHA FROM ABONOS WHERE FECHA LIKE '%/21';
SELECT CLIENTE_ID, NOMBRE, DIRECCION FROM CLIENTES2 WHERE NOMBRE LIKE'A%';

------------------------ IS NULL

SELECT CLIENTE_ID, NOMBRE, DIRECCION FROM CLIENTES2 WHERE CURP IS NULL;

------------------------ precedencia de operadores
SELECT MONTO, INTERES FROM PRESTAMOS WHERE INTERES > 7 AND MONTO > 50000;
SELECT MONTO, INTERES FROM PRESTAMOS WHERE INTERES < 7 AND MONTO < 50000 OR MONTO > 100000 ;

------------------------ ORDENACION  sintaxis completa de SELECT con la cláusula ORDER BY
SELECT FECHA, PRESTAMO_ID, MONTO, PRESTAMO_ID||'_'||FECHA||'_'||PRESTAMO_ID "ID GENERADO" FROM ABONOS ORDER BY FECHA;
SELECT PRESTAMO_ID, FECHA, MONTO, PRESTAMO_ID||'_'||FECHA||'_'||PRESTAMO_ID "ID GENERADO" FROM ABONOS ORDER BY PRESTAMO_ID;

------------------------ ORDENACION ASC Y DESC
SELECT PRESTAMO_ID, FECHA, MONTO, PRESTAMO_ID||'_'||FECHA||'_'||PRESTAMO_ID "ID GENERADO" FROM ABONOS ORDER BY PRESTAMO_ID DESC; --MAS RECIENTES
SELECT FECHA, PRESTAMO_ID, MONTO, PRESTAMO_ID||'_'||FECHA||'_'||PRESTAMO_ID "ID GENERADO" FROM ABONOS ORDER BY FECHA DESC; --MAS RECIENTES
SELECT FECHA, PRESTAMO_ID, MONTO, PRESTAMO_ID||'_'||FECHA||'_'||PRESTAMO_ID "ID GENERADO" FROM ABONOS ORDER BY MONTO ASC; --MENOR A MAYOR
SELECT FECHA, PRESTAMO_ID, MONTO, PRESTAMO_ID||'_'||FECHA||'_'||PRESTAMO_ID "ID GENERADO" FROM ABONOS ORDER BY MONTO DESC; --MAYOR A MENOR


------------------------ ORDENACION orden por número de columnas
SELECT FECHA, PRESTAMO_ID, MONTO, PRESTAMO_ID||'_'||FECHA||'_'||PRESTAMO_ID "ID GENERADO" FROM ABONOS ORDER BY 3,2,1;

------------------------ ORDENACION orden por número de columnas
SELECT CLIENTE_ID, NOMBRE, DIRECCION FROM CLIENTES2 order by CURP NULLS FIRST;












