SELECT * FROM ROL;
SELECT * FROM CLIENTES2;
SELECT * FROM MOVIMIENTOS;
SELECT * FROM ABONOS;
SELECT * FROM CUENTAS;
SELECT * FROM TARJETAS;
SELECT * FROM TIPO_TARJETA;
SELECT * FROM TIPO_CUENTA;



SELECT NOMBRE, DIRECCION FROM CLIENTES2;  

--La columna id_trabajo ha sido renombrada por la palabra identificador.
--No es un renombrado permanente, sólo se utiliza en la ejecución de la instrucción SELECT.
SELECT CLIENTE_ID AS IDENTIFICADOR, NOMBRE FROM CLIENTES2;
--FORMA 2 : NO HACE FALTA OCUPAR "AS", BASTA UN ESPACIO EN BLANCO
SELECT CLIENTE_ID IDENTIFICADOR, NOMBRE IDENTIDAD FROM CLIENTES2;
--FORMA 3 : BUSCA QUE SER MAS CLARO
SELECT CLIENTE_ID "IDENTIFICADOR PRIMARIO", NOMBRE FROM CLIENTES2;

--CALCULOS

SELECT PRESTAMO_ID, FECHA, MONTO, MONTO  * 1.16 "MONTO + IVA" FROM ABONOS;

--CONCATENACION DE TEXTOS
--EN ORACLE PARA CONCATENAR SE OCUPA :||
SELECT CUENTA_ID, NUM_TARJETA, TIPO_TARJETA_ID || '-' || EXPIRA "TERMINACION" 
FROM TARJETAS;

--CONDICIONALES && VALORES LOGICOS (AND, NOT, OR, <=, >=, <, >, [<> O !+ DISTINTO])
SELECT CUENTA_ID, MONTO FROM MOVIMIENTOS
WHERE MONTO >= 5000 AND MONTO <=7000; 

--BETWEEN : PERMITE OBTERNER DATOS QUE SE ENCUENTREN EN UN RANGO
SELECT CUENTA_ID, MONTO FROM MOVIMIENTOS
WHERE MONTO BETWEEN 2000 AND 5000;

--IN : PERMITE OBTENER REGISTROS CUYOS VALORES ESTEN EN UNA LISTA DE VALORES
SELECT ABONO_ID, FECHA, MONTO FROM ABONOS
WHERE MONTO IN (2000,4000,6000);

--LIKE : SE UTILIZA PARA COMPARAR TEXTO PRINCIPALMENTE
--       ('%' UNA SERIE DE CARACTERES) ('_' UN CARACTER CU7ALQUIERA)
SELECT NOMBRE FROM CLIENTES2
WHERE NOMBRE LIKE 'Juan%';

--IS NULL : SE UTILIZA PARA VALORAR SI UN DATO ES NULO
SELECT NUM_TARJETA, TIPO_TARJETA_ID FROM TARJETAS
WHERE NIVEL IS NULL;

--PRECADENCIA DE OPERADORES (ORDEN EN EL QUE SE EJECUTAN)
--(CON PARENTESIS SE PUEDE DAR PRIORIDAD)
--1 : *(Multiplicar) /(dividir)
--2 : + (Suma) - (Resta)
--3 : || (Concatenación)
--4 : Comparaciones (>, <, !=, ...)
--5 : IS NULL, IS NOT NULL, LIKE, IN, NOT IN
--6 : NOT, NOT BETWEEN
--7 : NOT
--8 : AND
--9 : OR

--ORDENACION :
--SIRVE PARA ORDENAR DE MANERA ACENDENTE O DECENDENTE, ACENDENTE ES LA MANERA POR DEFETO

SELECT MOV_ID, TIPO_OPERACION, MONTO
FROM MOVIMIENTOS
ORDER BY MONTO DESC;

SELECT MOV_ID, TIPO_OPERACION, MONTO
FROM MOVIMIENTOS
ORDER BY MONTO;

SELECT MOV_ID, TIPO_OPERACION, MONTO "OPERACION $"
FROM MOVIMIENTOS
ORDER BY "OPERACION $";
--SE UTILIZA EL NUMERO DE COLUMNA QUE ESTA DESPUES DE SELECT
SELECT MOV_ID, TIPO_OPERACION, MONTO "OPERACION $"
FROM MOVIMIENTOS
ORDER BY 3 DESC;

SELECT MOV_ID, TIPO_OPERACION, MONTO "OPERACION $"
FROM MOVIMIENTOS
ORDER BY MOV_ID, MONTO DESC;

--ORDENAMIENTO POR COLUMNAS
SELECT MOV_ID, TIPO_OPERACION, MONTO
FROM MOVIMIENTOS
ORDER BY 1 DESC, 3;

--VARIABLES DE SUSTITUCION
SELECT NOMBRE "NOMBRE COMPLETO" 
FROM CLIENTES2
WHERE CURP='&CURP';

SELECT &&MONTO
FROM ABONOS
ORDER BY &MONTO;