SELECT * FROM CLIENTES2;
SELECT NOMBRE AS NOMB FROM CLIENTES2;
--EL OPERADOR DE CONCATENAR TEXTO PERMITE UNIR DOS TEXTOS
SELECT CLIENTE_ID, NOMBRE,FECHA_NAC||'-'||NOMBRE FROM CLIENTES2;

--OPERADORES DE COMPARACION--
SELECT CUENTA_ID 
FROM MOVIMIENTOS 
WHERE CUENTA_ID < 5;

--VALORES LOGICOS
SELECT ROL_ID 
FROM ROL WHERE 
SUELDO >10000 AND SUELDO <45000;


--EL OPERADOR BETWEN NOS PERMITE OBTENER DATOS QUE SE ENCUENTEN EN UN RANGO
SELECT MOV_ID
FROM MOVIMIENTOS
WHERE MONTO BETWEEN 1000 AND 5000;

-- IN PERMINTE OBTENER REGISTROS CUYOS VALORES ESTAN DENTRO DE UNA LISTA DE VALORES

SELECT MOV_ID,TIPO_OPERACION,FECHA
FROM MOVIMIENTOS
WHERE TIPO_OPERACION IN ('DEPOSITO', 'TRANSFERENCIA','RETIRO');

--LIKE SE USA PARA BUSCAR COINCIDENCIAS EN CAPOS DE TEXTOS, APLICANDO PATRONES CON LOS SIMBOLOS %,_
SELECT CLIENTE_ID,NOMBRE,DIRECCION
FROM CLIENTES2
WHERE DIRECCION LIKE '%CALLE%';

--EL OPERADOR DESTINA A COMPROBAR SI UN DETERMINADO DATO ES NULO
SELECT CLIENTE_ID, NOMBRE
FROM CLIENTES2
WHERE CURP IS NULL;

--EXISTE TAMBIÉN LA EXPRESIÓN CONTRARIA: IS NOT NULL QUE DEVUELVE VERDADERO EN EL CASO CONTRARIO, ANTE CUALQUIER VALOR DISTINTO DE NULO.
SELECT CLIENTE_ID, NOMBRE
FROM CLIENTES2
WHERE CURP IS NOT NULL;

--lAS EXPRESIONES DE LA CLÁUSULA ORDER BY PUEDEN SER CUALQUIERA QUE HAGA REFERENCIA A UNA COLUMNA ASC O DESC

SELECT MOV_ID,MONTO
FROM MOVIMIENTOS
ORDER BY MONTO ASC ;

SELECT CLIENTE_ID, NOMBRE, FECHA_NAC
FROM CLIENTES2
ORDER BY FECHA_NAC DESC;











