//sintaxis sencilla del comando SELECT
SELECT * FROM ROL;
SELECT * FROM CLIENTES2;
SELECT * FROM MOVIMIENTOS;
SELECT * FROM ABONOS;
SELECT * FROM CUENTAS;
SELECT * FROM TARJETAS;
SELECT * FROM TIPO_TARJETA;
SELECT * FROM TIPO_CUENTA;

//CALCULOS ARITMETICS TABLA CUENTAS
SELECT
    CUENTA_ID,
    FECHA,
    TIPO_OPERACION,
    MONTO
FROM
    MOVIMIENTOS
WHERE
    CUENTA_ID = 3 AND MONTO > 2000;
    
SELECT
    CUENTA_ID,
    FECHA,
    TIPO_OPERACION,
    MONTO
FROM
    MOVIMIENTOS
WHERE
    TIPO_OPERACION = 'DEPOSITO' OR TIPO_OPERACION = 'RETIRO';

//AND y OR 
SELECT
    *
FROM
    MOVIMIENTOS
WHERE
    CUENTA_ID = 7 AND (TIPO_OPERACION = 'DEPOSITO' OR TIPO_OPERACION = 'RETIRO') AND MONTO > 3000;

//BETWEEN
SELECT * FROM MOVIMIENTOS
WHERE FECHA BETWEEN TO_DATE('2021-01-01', 'YYYY-MM-DD') AND TO_DATE('2021-12-31', 'YYYY-MM-DD');

//IN
SELECT * FROM MOVIMIENTOS
WHERE CUENTA_ID IN (3, 5, 9);

//CONCATENACION DE TEXTO TABLA CLIENTES2
SELECT
    NOMBRE || ', vive en: ' || DIRECCION AS informacion_cliente,
    CURP
FROM
    CLIENTES2;
    
//ORDER BY TABLA CLIENTES 2 COLUMNA ACENDETE 
SELECT
    NOMBRE,
    FECHA_NAC,
    CURP
FROM
    CLIENTES2
ORDER BY
    NOMBRE ASC; 
    
// DESENDENTE 
SELECT
    NOMBRE,
    FECHA_NAC
FROM
    CLIENTES2
ORDER BY
    FECHA_NAC DESC;
    
    
//ordenarlas alfabéticamente por NOMBRE.
SELECT
    NOMBRE,
    DIRECCION
FROM
    CLIENTES2
ORDER BY
    LENGTH(DIRECCION) ASC, -- Criterio principal: Longitud ascendente
    NOMBRE ASC;             -- Criterio secundario: Nombre ascendente


//NULLS 
SELECT NOMBRE, FECHA_NAC FROM CLIENTES2
ORDER BY FECHA_NAC DESC NULLS FIRST;

//VARIABLES DE SUSTITUCION
SELECT * FROM MOVIMIENTOS WHERE CUENTA_ID = &id_cuenta;

//COMANDO DEFINE
DEFINE departamento = 20;
DEFINE nombre_trabajo = 'MANAGER';

-- Definimos la cuenta que queremos consultar
DEFINE id_cuenta = 3;

//DEFINE CON WHERE
SELECT
    *
FROM
    MOVIMIENTOS
WHERE
    CUENTA_ID = &id_cuenta; 







